# Generated by Django 3.2.9 on 2021-11-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Paper_Metadata',
        ),
    ]
