# Generated by Django 3.2.9 on 2021-11-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_rename_test_paper_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('paper_id', models.IntegerField()),
                ('commenter_id', models.IntegerField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper_Like_Dislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('paper_id', models.IntegerField()),
                ('like', models.BooleanField()),
                ('dislike', models.BooleanField()),
            ],
        ),
    ]
