# Generated by Django 3.2.9 on 2021-11-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_paper_comment_paper_like_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_comment',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='paper_comment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='universal create time'),
        ),
        migrations.AlterField(
            model_name='paper_comment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='universal id'),
        ),
    ]
