# Generated by Django 3.2.9 on 2021-11-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20211115_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_like_dislike',
            name='dislike',
        ),
        migrations.AlterField(
            model_name='paper_like_dislike',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='universal create time'),
        ),
        migrations.AlterField(
            model_name='paper_like_dislike',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='universal id'),
        ),
    ]
