# Generated by Django 3.2.9 on 2021-11-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20211115_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper_comment',
            name='commenter_email',
            field=models.CharField(max_length=256, null=True, verbose_name='user email'),
        ),
        migrations.AddField(
            model_name='paper_comment',
            name='commenter_name',
            field=models.CharField(max_length=64, null=True, verbose_name='user fullname'),
        ),
    ]
