# Generated by Django 3.2.9 on 2021-11-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20211115_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper_comment',
            name='paper_id',
            field=models.CharField(max_length=1024, null=True, verbose_name='external paper id'),
        ),
        migrations.AlterField(
            model_name='paper_like_dislike',
            name='paper_id',
            field=models.CharField(max_length=1024, null=True, verbose_name='external paper id'),
        ),
    ]
