# Generated by Django 3.2.9 on 2021-11-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_paper_comment_paper_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper_comment',
            name='paper_name',
        ),
    ]
