version: "3.9"
services:
  web:
    container_name: scholar-hub-fe
    image: nginx
    volumes:
      - ./dist:/usr/share/nginx/html/scholar-hub/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
