# Generated by Django 3.2.9 on 2021-11-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IcdeRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='universal id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='universal create time')),
                ('user_id', models.BigIntegerField(verbose_name='id of the user')),
                ('paper_id', models.CharField(max_length=1024, verbose_name='external paper id')),
                ('team_id', models.BigIntegerField(null=True, verbose_name='id of the team')),
                ('team_name', models.CharField(max_length=1024, null=True, verbose_name='name of the team')),
                ('input_text', models.CharField(max_length=32768, verbose_name='operation input text')),
                ('operation_type', models.CharField(max_length=64, verbose_name='the type of the operation')),
                ('paper_title', models.CharField(max_length=1024, verbose_name='name of the paper')),
            ],
            options={
                'db_table': 'icde_icde_record',
            },
        ),
    ]
