# Generated by Django 3.2.9 on 2021-11-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icde', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icderecord',
            name='paper_id',
            field=models.BigIntegerField(null=True, unique=True, verbose_name='id of the paper'),
        ),
    ]
