# Generated by Django 3.2.9 on 2021-11-14 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='universal id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='universal create time')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='user nickname')),
                ('password', models.CharField(max_length=512, verbose_name='user password')),
                ('name', models.CharField(max_length=64, verbose_name='user fullname')),
                ('email', models.CharField(max_length=256, unique=True, verbose_name='user email')),
                ('area', models.JSONField(verbose_name='user research area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResearchTeam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='universal id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='universal create time')),
                ('name', models.CharField(max_length=512, verbose_name='team name')),
                ('leader_id', models.BigIntegerField(verbose_name='id of the leader')),
            ],
            options={
                'db_table': 'researcher_research_team',
            },
        ),
        migrations.CreateModel(
            name='TokenPool',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='universal id')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='universal create time')),
                ('holder_id', models.BigIntegerField(unique=True, verbose_name='id of the token holder')),
                ('token', models.CharField(max_length=2048, verbose_name='token')),
            ],
            options={
                'db_table': 'researcher_token_pool',
            },
        ),
    ]
