# Generated by Django 3.2.9 on 2021-11-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcher',
            name='title',
            field=models.CharField(default='', max_length=64, verbose_name='user title'),
        ),
    ]
