# Generated by Django 3.2.9 on 2021-11-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='email',
            field=models.CharField(max_length=256, unique=True, verbose_name='user email'),
        ),
    ]
